background_opacity 0.1
font_family M Plus 1 Code
font_size 18

background #1f2020
cursor     #CCCCCC
selection_background #7fffd4

foreground #E0E0E0

color0  #3A3A3A
color1  #CC5555
color2  #66AA66
color3  #DDAA66
color4  #6699CC
color5  #AA88CC
color6  #66CCCC
color7  #CFCFCF

color8  #5A5A5A
color9  #FF7777
color10 #88FFAA
color11 #FFE599
color12 #99CCFF
color13 #DDAAFF
color14 #99FFFF
color15 #F0F0F0
