#!/bin/sh

DIR="$HOME/Documents/Screenshots"
mkdir -p "$DIR"

file="$DIR/$(date +%Y%m%d_%H%M%S).png"

geom=$(slurp) || exit 1

[ -n "$geom" ] || exit 0

grim -g "$geom" "$file" && wl-copy < "$file"

aplay /usr/share/sounds/speech-dispatcher/gummy-cat-2.wav
