background {
    monitor =
    path = $HOME/.current_wallpaper
    blur_size = 4
    blur_passes = 3
    noise = 0.0117
    #contrast = 1.3000
    #vibrancy = 0.2100
    #vibrancy_darkness = 0.0
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $color6
    font_size = 112
    font_family = M Plus 1 Code
    position = 0, 220
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:180000] echo "Hi $USER :)"
    color = $color7
    font_size = 22
    font_family = M Plus 1 Code
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 30
    font_size = 22
    outline_thickness = 3
    rounding = 5
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    placeholder_text = Password...
    position = 0, 0
    halign = center
    valign = center
}
