general {
    border_size = 2
    gaps_in = 0, 0, 5, 5
    gaps_out = 0, 10, 10, 10
    col.inactive_border = rgba(E0E0E0FF)
    col.active_border = rgba(E0E0E0FF)
    layout = dwindle
    resize_on_border = true
    snap {
        enabled = false
    }
}

decoration {
    rounding = 0
    rounding_power = 0
    blur {
        enabled = yes
        size = 5
        passes = 5
        #xray = yes
        noise = 0.03
        contrast = 1
        brightness = 0.4
        vibrancy = 0
        vibrancy_darkness = 0
    }
    shadow {
        enabled = yes
        sharp = yes
        range = 1
    }
}

animations {
    enabled = no
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
