#!/bin/sh

DIR="$HOME/Documents/Screenshots"
mkdir -p "$DIR"

file="$DIR/$(date +%Y%m%d_%H%M%S).png"

sleep 0.5; grim - | tee "$file" | wl-copy

aplay /usr/share/sounds/speech-dispatcher/gummy-cat-2.wav

